/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as I18nDemoRouteImport } from './routes/i18n-demo'
import { Route as FilamentRouteImport } from './routes/filament'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const I18nDemoRoute = I18nDemoRouteImport.update({
  id: '/i18n-demo',
  path: '/i18n-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FilamentRoute = FilamentRouteImport.update({
  id: '/filament',
  path: '/filament',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/filament': typeof FilamentRoute
  '/i18n-demo': typeof I18nDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/filament': typeof FilamentRoute
  '/i18n-demo': typeof I18nDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/filament': typeof FilamentRoute
  '/i18n-demo': typeof I18nDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/app' | '/filament' | '/i18n-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/app' | '/filament' | '/i18n-demo'
  id: '__root__' | '/' | '/about' | '/app' | '/filament' | '/i18n-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  FilamentRoute: typeof FilamentRoute
  I18nDemoRoute: typeof I18nDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/i18n-demo': {
      id: '/i18n-demo'
      path: '/i18n-demo'
      fullPath: '/i18n-demo'
      preLoaderRoute: typeof I18nDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filament': {
      id: '/filament'
      path: '/filament'
      fullPath: '/filament'
      preLoaderRoute: typeof FilamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  FilamentRoute: FilamentRoute,
  I18nDemoRoute: I18nDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
