add_executable(print_apply_validate_smoke_tests
	${_TEST_NAME}_tests.cpp
	test_print_init_smoke.cpp
)
target_link_libraries(print_apply_validate_smoke_tests PRIVATE test_common libslic3r_print_apply_validate_core)
set_property(TARGET print_apply_validate_smoke_tests PROPERTY FOLDER "tests")
add_test(print_apply_validate_smoke_tests print_apply_validate_smoke_tests ${CATCH_EXTRA_ARGS})
