add_executable(print_process_core_smoke_tests
	${_TEST_NAME}_tests.cpp
	test_print_solid_layers_smoke.cpp
)
target_link_libraries(print_process_core_smoke_tests PRIVATE test_common libslic3r_print_process_core)
set_property(TARGET print_process_core_smoke_tests PROPERTY FOLDER "tests")
add_test(print_process_core_smoke_tests print_process_core_smoke_tests ${CATCH_EXTRA_ARGS})
