add_executable(print_perimeters_stage_smoke_tests
	${_TEST_NAME}_tests.cpp
	test_print_process_smoke.cpp
)
target_link_libraries(print_perimeters_stage_smoke_tests PRIVATE test_common libslic3r_print_perimeters_core)
set_property(TARGET print_perimeters_stage_smoke_tests PROPERTY FOLDER "tests")
add_test(print_perimeters_stage_smoke_tests print_perimeters_stage_smoke_tests ${CATCH_EXTRA_ARGS})
