#ifndef slic3r_BBL_Shader_Programs_hpp_
#define slic3r_BBL_Shader_Programs_hpp_

const std::string gouraud_fs =
"#version 110\r\n"
"\r\n"
"const vec3 ZERO = vec3(0.0, 0.0, 0.0);\r\n"
"//BBS: add grey and orange\r\n"
"//const vec3 GREY = vec3(0.9, 0.9, 0.9);\r\n"
"const vec3 ORANGE = vec3(0.8, 0.4, 0.0);\r\n"
"const float EPSILON = 0.0001;\r\n"
"\r\n"
"struct PrintVolumeDetection\r\n"
"{\r\n"
"	// 0 = rectangle, 1 = circle, 2 = custom, 3 = invalid\r\n"
"	int type;\r\n"
"    // type = 0 (rectangle):\r\n"
"    // x = min.x, y = min.y, z = max.x, w = max.y\r\n"
"    // type = 1 (circle):\r\n"
"    // x = center.x, y = center.y, z = radius\r\n"
"	vec4 xy_data;\r\n"
"    // x = min z, y = max z\r\n"
"	vec2 z_data;\r\n"
"};\r\n"
"\r\n"
"struct SlopeDetection\r\n"
"{\r\n"
"    bool actived;\r\n"
"	float normal_z;\r\n"
"    mat3 volume_world_normal_matrix;\r\n"
"};\r\n"
"\r\n"
"uniform vec4 uniform_color;\r\n"
"uniform SlopeDetection slope;\r\n"
"\r\n"
"//BBS: add outline_color\r\n"
"uniform bool is_outline;\r\n"
"\r\n"
"uniform bool offset_depth_buffer;\r\n"
"\r\n"
"#ifdef ENABLE_ENVIRONMENT_MAP\r\n"
"    uniform sampler2D environment_tex;\r\n"
"    uniform bool use_environment_tex;\r\n"
"#endif // ENABLE_ENVIRONMENT_MAP\r\n"
"\r\n"
"varying vec3 clipping_planes_dots;\r\n"
"\r\n"
"// x = diffuse, y = specular;\r\n"
"varying vec2 intensity;\r\n"
"\r\n"
"uniform PrintVolumeDetection print_volume;\r\n"
"\r\n"
"varying vec4 model_pos;\r\n"
"varying vec4 world_pos;\r\n"
"varying float world_normal_z;\r\n"
"varying vec3 eye_normal;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    if (any(lessThan(clipping_planes_dots, ZERO)))\r\n"
"        discard;\r\n"
"    vec3  color = uniform_color.rgb;\r\n"
"    float alpha = uniform_color.a;\r\n"
"\r\n"
"    if (slope.actived && world_normal_z < slope.normal_z - EPSILON) {\r\n"
"        //color = vec3(0.7, 0.7, 1.0);\r\n"
"        color = ORANGE;\r\n"
"        alpha = 1.0;\r\n"
"    }\r\n"
"	\r\n"
"    // if the fragment is outside the print volume -> use darker color\r\n"
"	vec3 pv_check_min = ZERO;\r\n"
"	vec3 pv_check_max = ZERO;\r\n"
"    if (print_volume.type == 0) {\r\n"
"		// rectangle\r\n"
"		pv_check_min = world_pos.xyz - vec3(print_volume.xy_data.x, print_volume.xy_data.y, print_volume.z_data.x);\r\n"
"		pv_check_max = world_pos.xyz - vec3(print_volume.xy_data.z, print_volume.xy_data.w, print_volume.z_data.y);\r\n"
"	}\r\n"
"	else if (print_volume.type == 1) {\r\n"
"		// circle\r\n"
"		float delta_radius = print_volume.xy_data.z - distance(world_pos.xy, print_volume.xy_data.xy);\r\n"
"		pv_check_min = vec3(delta_radius, 0.0, world_pos.z - print_volume.z_data.x);\r\n"
"		pv_check_max = vec3(0.0, 0.0, world_pos.z - print_volume.z_data.y);\r\n"
"	}	\r\n"
"	color = (any(lessThan(pv_check_min, ZERO)) || any(greaterThan(pv_check_max, ZERO))) ? mix(color, ZERO, 0.3333) : color;\r\n"
"	//BBS: add outline_color\r\n"
"	if (is_outline)\r\n"
"		gl_FragColor = uniform_color;\r\n"
"#ifdef ENABLE_ENVIRONMENT_MAP\r\n"
"  else if (use_environment_tex)\r\n"
"        gl_FragColor = vec4(0.45 * texture2D(environment_tex, normalize(eye_normal).xy * 0.5 + 0.5).xyz + 0.8 * color * intensity.x, alpha);\r\n"
"#endif\r\n"
"	else\r\n"
"        gl_FragColor = vec4(vec3(intensity.y) + color * intensity.x, alpha);\r\n"
"		\r\n"
"    // In the support painting gizmo and the seam painting gizmo are painted triangles rendered over the already\r\n"
"    // rendered object. To resolved z-fighting between previously rendered object and painted triangles, values\r\n"
"    // inside the depth buffer are offset by small epsilon for painted triangles inside those gizmos.\r\n"
"    gl_FragDepth = gl_FragCoord.z - (offset_depth_buffer ? EPSILON : 0.0);\r\n"
"}\r\n"
;

const std::string gouraud_vs =
"#version 110\r\n"
"\r\n"
"#define INTENSITY_CORRECTION 0.6\r\n"
"\r\n"
"// normalized values for (-0.6/1.31, 0.6/1.31, 1./1.31)\r\n"
"const vec3 LIGHT_TOP_DIR = vec3(-0.4574957, 0.4574957, 0.7624929);\r\n"
"#define LIGHT_TOP_DIFFUSE    (0.8 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SPECULAR   (0.125 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SHININESS  20.0\r\n"
"\r\n"
"// normalized values for (1./1.43, 0.2/1.43, 1./1.43)\r\n"
"const vec3 LIGHT_FRONT_DIR = vec3(0.6985074, 0.1397015, 0.6985074);\r\n"
"#define LIGHT_FRONT_DIFFUSE  (0.3 * INTENSITY_CORRECTION)\r\n"
"//#define LIGHT_FRONT_SPECULAR (0.0 * INTENSITY_CORRECTION)\r\n"
"//#define LIGHT_FRONT_SHININESS 5.0\r\n"
"\r\n"
"#define INTENSITY_AMBIENT    0.3\r\n"
"\r\n"
"const vec3 ZERO = vec3(0.0, 0.0, 0.0);\r\n"
"\r\n"
"struct SlopeDetection\r\n"
"{\r\n"
"    bool actived;\r\n"
"	float normal_z;\r\n"
"    mat3 volume_world_normal_matrix;\r\n"
"};\r\n"
"\r\n"
"uniform mat4 volume_world_matrix;\r\n"
"uniform SlopeDetection slope;\r\n"
"\r\n"
"// Clipping plane, x = min z, y = max z. Used by the FFF and SLA previews to clip with a top / bottom plane.\r\n"
"uniform vec2 z_range;\r\n"
"// Clipping plane - general orientation. Used by the SLA gizmo.\r\n"
"uniform vec4 clipping_plane;\r\n"
"\r\n"
"// x = diffuse, y = specular;\r\n"
"varying vec2 intensity;\r\n"
"\r\n"
"varying vec3 clipping_planes_dots;\r\n"
"\r\n"
"varying vec4 model_pos;\r\n"
"varying vec4 world_pos;\r\n"
"varying float world_normal_z;\r\n"
"varying vec3 eye_normal;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"	// First transform the normal into camera space and normalize the result.\r\n"
"	eye_normal = normalize(gl_NormalMatrix * gl_Normal);\r\n"
"\r\n"
"	// Compute the cos of the angle between the normal and lights direction. The light is directional so the direction is constant for every vertex.\r\n"
"	// Since these two are normalized the cosine is the dot product. We also need to clamp the result to the [0,1] range.\r\n"
"	float NdotL = max(dot(eye_normal, LIGHT_TOP_DIR), 0.0);\r\n"
"\r\n"
"	intensity.x = INTENSITY_AMBIENT + NdotL * LIGHT_TOP_DIFFUSE;\r\n"
"	vec3 position = (gl_ModelViewMatrix * gl_Vertex).xyz;\r\n"
"	intensity.y = LIGHT_TOP_SPECULAR * pow(max(dot(-normalize(position), reflect(-LIGHT_TOP_DIR, eye_normal)), 0.0), LIGHT_TOP_SHININESS);\r\n"
"\r\n"
"	// Perform the same lighting calculation for the 2nd light source (no specular applied).\r\n"
"	NdotL = max(dot(eye_normal, LIGHT_FRONT_DIR), 0.0);\r\n"
"	intensity.x += NdotL * LIGHT_FRONT_DIFFUSE;\r\n"
"\r\n"
"    model_pos = gl_Vertex;\r\n"
"    // Point in homogenous coordinates.\r\n"
"    world_pos = volume_world_matrix * gl_Vertex;\r\n"
"\r\n"
"    // z component of normal vector in world coordinate used for slope shading\r\n"
"    world_normal_z = slope.actived ? (normalize(slope.volume_world_normal_matrix * gl_Normal)).z : 0.0;\r\n"
"\r\n"
"    gl_Position = ftransform();\r\n"
"    // Fill in the scalars for fragment shader clipping. Fragments with any of these components lower than zero are discarded.\r\n"
"    clipping_planes_dots = vec3(dot(world_pos, clipping_plane), world_pos.z - z_range.x, z_range.y - world_pos.z);\r\n"
"}\r\n"
;

const std::string gouraud_light_fs =
"#version 110\r\n"
"\r\n"
"uniform vec4 uniform_color;\r\n"
"uniform float emission_factor;\r\n"
"\r\n"
"// x = tainted, y = specular;\r\n"
"varying vec2 intensity;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_FragColor = vec4(vec3(intensity.y) + uniform_color.rgb * (intensity.x + emission_factor), uniform_color.a);\r\n"
"}\r\n"
;

const std::string gouraud_light_vs =
"#version 110\r\n"
"\r\n"
"#define INTENSITY_CORRECTION 0.6\r\n"
"\r\n"
"// normalized values for (-0.6/1.31, 0.6/1.31, 1./1.31)\r\n"
"const vec3 LIGHT_TOP_DIR = vec3(-0.4574957, 0.4574957, 0.7624929);\r\n"
"#define LIGHT_TOP_DIFFUSE    (0.8 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SPECULAR   (0.125 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SHININESS  20.0\r\n"
"\r\n"
"// normalized values for (1./1.43, 0.2/1.43, 1./1.43)\r\n"
"const vec3 LIGHT_FRONT_DIR = vec3(0.6985074, 0.1397015, 0.6985074);\r\n"
"#define LIGHT_FRONT_DIFFUSE  (0.3 * INTENSITY_CORRECTION)\r\n"
"\r\n"
"#define INTENSITY_AMBIENT    0.3\r\n"
"\r\n"
"// x = tainted, y = specular;\r\n"
"varying vec2 intensity;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    // First transform the normal into camera space and normalize the result.\r\n"
"    vec3 normal = normalize(gl_NormalMatrix * gl_Normal);\r\n"
"    \r\n"
"    // Compute the cos of the angle between the normal and lights direction. The light is directional so the direction is constant for every vertex.\r\n"
"    // Since these two are normalized the cosine is the dot product. We also need to clamp the result to the [0,1] range.\r\n"
"    float NdotL = max(dot(normal, LIGHT_TOP_DIR), 0.0);\r\n"
"\r\n"
"    intensity.x = INTENSITY_AMBIENT + NdotL * LIGHT_TOP_DIFFUSE;\r\n"
"    vec3 position = (gl_ModelViewMatrix * gl_Vertex).xyz;\r\n"
"    intensity.y = LIGHT_TOP_SPECULAR * pow(max(dot(-normalize(position), reflect(-LIGHT_TOP_DIR, normal)), 0.0), LIGHT_TOP_SHININESS);\r\n"
"\r\n"
"    // Perform the same lighting calculation for the 2nd light source (no specular applied).\r\n"
"    NdotL = max(dot(normal, LIGHT_FRONT_DIR), 0.0);\r\n"
"    intensity.x += NdotL * LIGHT_FRONT_DIFFUSE;\r\n"
"\r\n"
"    gl_Position = ftransform();\r\n"
"}\r\n"
;

const std::string gouraud_light_instanced_fs =
"#version 110\r\n"
"\r\n"
"uniform vec4 uniform_color;\r\n"
"uniform float emission_factor;\r\n"
"\r\n"
"// x = tainted, y = specular;\r\n"
"varying vec2 intensity;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_FragColor = vec4(vec3(intensity.y) + uniform_color.rgb * (intensity.x + emission_factor), uniform_color.a);\r\n"
"}\r\n"
;

const std::string gouraud_light_instanced_vs =
"#version 110\r\n"
"\r\n"
"#define INTENSITY_CORRECTION 0.6\r\n"
"\r\n"
"// normalized values for (-0.6/1.31, 0.6/1.31, 1./1.31)\r\n"
"const vec3 LIGHT_TOP_DIR = vec3(-0.4574957, 0.4574957, 0.7624929);\r\n"
"#define LIGHT_TOP_DIFFUSE    (0.8 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SPECULAR   (0.125 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SHININESS  20.0\r\n"
"\r\n"
"// normalized values for (1./1.43, 0.2/1.43, 1./1.43)\r\n"
"const vec3 LIGHT_FRONT_DIR = vec3(0.6985074, 0.1397015, 0.6985074);\r\n"
"#define LIGHT_FRONT_DIFFUSE  (0.3 * INTENSITY_CORRECTION)\r\n"
"\r\n"
"#define INTENSITY_AMBIENT    0.3\r\n"
"\r\n"
"// vertex attributes\r\n"
"attribute vec3 v_position;\r\n"
"attribute vec3 v_normal;\r\n"
"// instance attributes\r\n"
"attribute vec3 i_offset;\r\n"
"attribute vec2 i_scales;\r\n"
"\r\n"
"// x = tainted, y = specular;\r\n"
"varying vec2 intensity;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    // First transform the normal into camera space and normalize the result.\r\n"
"    vec3 eye_normal = normalize(gl_NormalMatrix * v_normal);\r\n"
"    \r\n"
"    // Compute the cos of the angle between the normal and lights direction. The light is directional so the direction is constant for every vertex.\r\n"
"    // Since these two are normalized the cosine is the dot product. We also need to clamp the result to the [0,1] range.\r\n"
"    float NdotL = max(dot(eye_normal, LIGHT_TOP_DIR), 0.0);\r\n"
"\r\n"
"    intensity.x = INTENSITY_AMBIENT + NdotL * LIGHT_TOP_DIFFUSE;\r\n"
"    vec4 world_position = vec4(v_position * vec3(vec2(1.5 * i_scales.x), 1.5 * i_scales.y) + i_offset - vec3(0.0, 0.0, 0.5 * i_scales.y), 1.0);\r\n"
"    vec3 eye_position = (gl_ModelViewMatrix * world_position).xyz;\r\n"
"    intensity.y = LIGHT_TOP_SPECULAR * pow(max(dot(-normalize(eye_position), reflect(-LIGHT_TOP_DIR, eye_normal)), 0.0), LIGHT_TOP_SHININESS);\r\n"
"\r\n"
"    // Perform the same lighting calculation for the 2nd light source (no specular applied).\r\n"
"    NdotL = max(dot(eye_normal, LIGHT_FRONT_DIR), 0.0);\r\n"
"    intensity.x += NdotL * LIGHT_FRONT_DIFFUSE;\r\n"
"\r\n"
"    gl_Position = gl_ProjectionMatrix * vec4(eye_position, 1.0);\r\n"
"}\r\n"
;

const std::string mm_contour_fs =
"#version 110\r\n"
"\r\n"
"const float EPSILON = 0.0001;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);\r\n"
"    // Values inside depth buffer for fragments of the contour of a selected area are offset\r\n"
"    // by small epsilon to solve z-fighting between painted triangles and contour lines.\r\n"
"    gl_FragDepth = gl_FragCoord.z - EPSILON;\r\n"
"}\r\n"
;

const std::string mm_contour_vs =
"#version 110\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_Position = ftransform();\r\n"
"}\r\n"
;

const std::string mm_gouraud_fs =
"#version 110\r\n"
"\r\n"
"#define INTENSITY_CORRECTION 0.6\r\n"
"\r\n"
"// normalized values for (-0.6/1.31, 0.6/1.31, 1./1.31)\r\n"
"const vec3 LIGHT_TOP_DIR = vec3(-0.4574957, 0.4574957, 0.7624929);\r\n"
"#define LIGHT_TOP_DIFFUSE    (0.8 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SPECULAR   (0.125 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SHININESS  20.0\r\n"
"\r\n"
"// normalized values for (1./1.43, 0.2/1.43, 1./1.43)\r\n"
"const vec3 LIGHT_FRONT_DIR = vec3(0.6985074, 0.1397015, 0.6985074);\r\n"
"#define LIGHT_FRONT_DIFFUSE  (0.3 * INTENSITY_CORRECTION)\r\n"
"\r\n"
"#define INTENSITY_AMBIENT    0.3\r\n"
"\r\n"
"const vec3  ZERO    = vec3(0.0, 0.0, 0.0);\r\n"
"const float EPSILON = 0.0001;\r\n"
"\r\n"
"uniform vec4 uniform_color;\r\n"
"\r\n"
"varying vec3 clipping_planes_dots;\r\n"
"varying vec4 model_pos;\r\n"
"\r\n"
"uniform bool volume_mirrored;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    if (any(lessThan(clipping_planes_dots, ZERO)))\r\n"
"        discard;\r\n"
"    vec3  color = uniform_color.rgb;\r\n"
"    float alpha = uniform_color.a;\r\n"
"\r\n"
"    vec3 triangle_normal = normalize(cross(dFdx(model_pos.xyz), dFdy(model_pos.xyz)));\r\n"
"#ifdef FLIP_TRIANGLE_NORMALS\r\n"
"    triangle_normal = -triangle_normal;\r\n"
"#endif\r\n"
"\r\n"
"    if (volume_mirrored)\r\n"
"        triangle_normal = -triangle_normal;\r\n"
"\r\n"
"    // First transform the normal into camera space and normalize the result.\r\n"
"    vec3 eye_normal = normalize(gl_NormalMatrix * triangle_normal);\r\n"
"\r\n"
"    // Compute the cos of the angle between the normal and lights direction. The light is directional so the direction is constant for every vertex.\r\n"
"    // Since these two are normalized the cosine is the dot product. We also need to clamp the result to the [0,1] range.\r\n"
"    float NdotL = max(dot(eye_normal, LIGHT_TOP_DIR), 0.0);\r\n"
"\r\n"
"    // x = diffuse, y = specular;\r\n"
"    vec2 intensity = vec2(0.0, 0.0);\r\n"
"    intensity.x = INTENSITY_AMBIENT + NdotL * LIGHT_TOP_DIFFUSE;\r\n"
"    vec3 position = (gl_ModelViewMatrix * model_pos).xyz;\r\n"
"    intensity.y = LIGHT_TOP_SPECULAR * pow(max(dot(-normalize(position), reflect(-LIGHT_TOP_DIR, eye_normal)), 0.0), LIGHT_TOP_SHININESS);\r\n"
"\r\n"
"    // Perform the same lighting calculation for the 2nd light source (no specular applied).\r\n"
"    NdotL = max(dot(eye_normal, LIGHT_FRONT_DIR), 0.0);\r\n"
"    intensity.x += NdotL * LIGHT_FRONT_DIFFUSE;\r\n"
"\r\n"
"    gl_FragColor = vec4(vec3(intensity.y) + color * intensity.x, alpha);\r\n"
"}\r\n"
;

const std::string mm_gouraud_fs_os_arm =
"#version 110\r\n"
"#define FLIP_TRIANGLE_NORMALS\r\n"
"#define INTENSITY_CORRECTION 0.6\r\n"
"\r\n"
"// normalized values for (-0.6/1.31, 0.6/1.31, 1./1.31)\r\n"
"const vec3 LIGHT_TOP_DIR = vec3(-0.4574957, 0.4574957, 0.7624929);\r\n"
"#define LIGHT_TOP_DIFFUSE    (0.8 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SPECULAR   (0.125 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SHININESS  20.0\r\n"
"\r\n"
"// normalized values for (1./1.43, 0.2/1.43, 1./1.43)\r\n"
"const vec3 LIGHT_FRONT_DIR = vec3(0.6985074, 0.1397015, 0.6985074);\r\n"
"#define LIGHT_FRONT_DIFFUSE  (0.3 * INTENSITY_CORRECTION)\r\n"
"\r\n"
"#define INTENSITY_AMBIENT    0.3\r\n"
"\r\n"
"const vec3  ZERO    = vec3(0.0, 0.0, 0.0);\r\n"
"const float EPSILON = 0.0001;\r\n"
"\r\n"
"uniform vec4 uniform_color;\r\n"
"\r\n"
"varying vec3 clipping_planes_dots;\r\n"
"varying vec4 model_pos;\r\n"
"\r\n"
"uniform bool volume_mirrored;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    if (any(lessThan(clipping_planes_dots, ZERO)))\r\n"
"        discard;\r\n"
"    vec3  color = uniform_color.rgb;\r\n"
"    float alpha = uniform_color.a;\r\n"
"\r\n"
"    vec3 triangle_normal = normalize(cross(dFdx(model_pos.xyz), dFdy(model_pos.xyz)));\r\n"
"#ifdef FLIP_TRIANGLE_NORMALS\r\n"
"    triangle_normal = -triangle_normal;\r\n"
"#endif\r\n"
"\r\n"
"    if (volume_mirrored)\r\n"
"        triangle_normal = -triangle_normal;\r\n"
"\r\n"
"    // First transform the normal into camera space and normalize the result.\r\n"
"    vec3 eye_normal = normalize(gl_NormalMatrix * triangle_normal);\r\n"
"\r\n"
"    // Compute the cos of the angle between the normal and lights direction. The light is directional so the direction is constant for every vertex.\r\n"
"    // Since these two are normalized the cosine is the dot product. We also need to clamp the result to the [0,1] range.\r\n"
"    float NdotL = max(dot(eye_normal, LIGHT_TOP_DIR), 0.0);\r\n"
"\r\n"
"    // x = diffuse, y = specular;\r\n"
"    vec2 intensity = vec2(0.0, 0.0);\r\n"
"    intensity.x = INTENSITY_AMBIENT + NdotL * LIGHT_TOP_DIFFUSE;\r\n"
"    vec3 position = (gl_ModelViewMatrix * model_pos).xyz;\r\n"
"    intensity.y = LIGHT_TOP_SPECULAR * pow(max(dot(-normalize(position), reflect(-LIGHT_TOP_DIR, eye_normal)), 0.0), LIGHT_TOP_SHININESS);\r\n"
"\r\n"
"    // Perform the same lighting calculation for the 2nd light source (no specular applied).\r\n"
"    NdotL = max(dot(eye_normal, LIGHT_FRONT_DIR), 0.0);\r\n"
"    intensity.x += NdotL * LIGHT_FRONT_DIFFUSE;\r\n"
"\r\n"
"    gl_FragColor = vec4(vec3(intensity.y) + color * intensity.x, alpha);\r\n"
"}\r\n"
;

const std::string mm_gouraud_vs =
"#version 110\r\n"
"\r\n"
"const vec3 ZERO = vec3(0.0, 0.0, 0.0);\r\n"
"\r\n"
"uniform mat4 volume_world_matrix;\r\n"
"// Clipping plane, x = min z, y = max z. Used by the FFF and SLA previews to clip with a top / bottom plane.\r\n"
"uniform vec2 z_range;\r\n"
"// Clipping plane - general orientation. Used by the SLA gizmo.\r\n"
"uniform vec4 clipping_plane;\r\n"
"\r\n"
"varying vec3 clipping_planes_dots;\r\n"
"varying vec4 model_pos;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    model_pos = gl_Vertex;\r\n"
"    // Point in homogenous coordinates.\r\n"
"    vec4 world_pos = volume_world_matrix * gl_Vertex;\r\n"
"\r\n"
"    gl_Position = ftransform();\r\n"
"    // Fill in the scalars for fragment shader clipping. Fragments with any of these components lower than zero are discarded.\r\n"
"    clipping_planes_dots = vec3(dot(world_pos, clipping_plane), world_pos.z - z_range.x, z_range.y - world_pos.z);\r\n"
"}\r\n"
;

const std::string mm_gouraud_vs_os_arm =
"#version 110\r\n"
"#define FLIP_TRIANGLE_NORMALS\r\n"
"const vec3 ZERO = vec3(0.0, 0.0, 0.0);\r\n"
"\r\n"
"uniform mat4 volume_world_matrix;\r\n"
"// Clipping plane, x = min z, y = max z. Used by the FFF and SLA previews to clip with a top / bottom plane.\r\n"
"uniform vec2 z_range;\r\n"
"// Clipping plane - general orientation. Used by the SLA gizmo.\r\n"
"uniform vec4 clipping_plane;\r\n"
"\r\n"
"varying vec3 clipping_planes_dots;\r\n"
"varying vec4 model_pos;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    model_pos = gl_Vertex;\r\n"
"    // Point in homogenous coordinates.\r\n"
"    vec4 world_pos = volume_world_matrix * gl_Vertex;\r\n"
"\r\n"
"    gl_Position = ftransform();\r\n"
"    // Fill in the scalars for fragment shader clipping. Fragments with any of these components lower than zero are discarded.\r\n"
"    clipping_planes_dots = vec3(dot(world_pos, clipping_plane), world_pos.z - z_range.x, z_range.y - world_pos.z);\r\n"
"}\r\n"
;

const std::string options_110_fs =
"#version 110\r\n"
"\r\n"
"uniform vec4 uniform_color;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_FragColor = uniform_color;\r\n"
"}\r\n"
;

const std::string options_110_vs =
"#version 110\r\n"
"\r\n"
"uniform bool use_fixed_screen_size;\r\n"
"uniform float zoom;\r\n"
"uniform float point_size;\r\n"
"uniform float near_plane_height;\r\n"
"\r\n"
"float fixed_screen_size()\r\n"
"{\r\n"
"    return point_size;\r\n"
"}\r\n"
"\r\n"
"float fixed_world_size()\r\n"
"{\r\n"
"    return (gl_Position.w == 1.0) ? zoom * near_plane_height * point_size : near_plane_height * point_size / gl_Position.w;\r\n"
"}\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_Position = ftransform();\r\n"
"    gl_PointSize = use_fixed_screen_size ? fixed_screen_size() : fixed_world_size();\r\n"
"}\r\n"
;

const std::string options_120_fs =
"// version 120 is needed for gl_PointCoord\r\n"
"#version 120\r\n"
"\r\n"
"uniform vec4 uniform_color;\r\n"
"uniform float percent_outline_radius;\r\n"
"uniform float percent_center_radius;\r\n"
"\r\n"
"vec4 calc_color(float radius, vec4 color)\r\n"
"{\r\n"
"    return ((radius < percent_center_radius) || (radius > 1.0 - percent_outline_radius)) ?\r\n"
"            vec4(0.5 * color.rgb, color.a) : color;\r\n"
"}\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    vec2 pos = (gl_PointCoord - 0.5) * 2.0;\r\n"
"    float radius = length(pos);\r\n"
"    if (radius > 1.0)\r\n"
"        discard;\r\n"
"\r\n"
"    gl_FragColor = calc_color(radius, uniform_color);\r\n"
"}\r\n"
;

const std::string options_120_vs =
"#version 120\r\n"
"\r\n"
"uniform bool use_fixed_screen_size;\r\n"
"uniform float zoom;\r\n"
"uniform float point_size;\r\n"
"uniform float near_plane_height;\r\n"
"\r\n"
"float fixed_screen_size()\r\n"
"{\r\n"
"    return point_size;\r\n"
"}\r\n"
"\r\n"
"float fixed_world_size()\r\n"
"{\r\n"
"    return (gl_Position.w == 1.0) ? zoom * near_plane_height * point_size : near_plane_height * point_size / gl_Position.w;\r\n"
"}\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_Position = ftransform();\r\n"
"    gl_PointSize = use_fixed_screen_size ? fixed_screen_size() : fixed_world_size();\r\n"
"}\r\n"
;

const std::string outline_fs =
"#version 110\r\n"
"\r\n"
"const vec3 ORANGE = vec3(0.8, 0.4, 0.0);\r\n"
"uniform vec4 uniform_color;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_FragColor = uniform_color;\r\n"
"	//gl_FragColor = vec4(ORANGE, 1.0);\r\n"
"}\r\n"
;

const std::string outline_vs =
"#version 110\r\n"
"\r\n"
"attribute vec4 v_position;\r\n"
"attribute vec2 v_tex_coords;\r\n"
"\r\n"
"varying vec2 tex_coords;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_Position = ftransform();\r\n"
"    tex_coords = v_tex_coords;\r\n"
"}\r\n"
;

const std::string printbed_fs =
"#version 110\r\n"
"\r\n"
"const vec3 back_color_dark = vec3(0.235, 0.235, 0.235);\r\n"
"const vec3 back_color_light = vec3(0.365, 0.365, 0.365);\r\n"
"\r\n"
"uniform sampler2D texture;\r\n"
"uniform bool transparent_background;\r\n"
"uniform bool svg_source;\r\n"
"\r\n"
"varying vec2 tex_coords;\r\n"
"\r\n"
"vec4 svg_color()\r\n"
"{\r\n"
"    // takes foreground from texture\r\n"
"    vec4 fore_color = texture2D(texture, tex_coords);\r\n"
"\r\n"
"    // calculates radial gradient\r\n"
"    vec3 back_color = vec3(mix(back_color_light, back_color_dark, smoothstep(0.0, 0.5, length(abs(tex_coords.xy) - vec2(0.5)))));\r\n"
"\r\n"
"    // blends foreground with background\r\n"
"    return vec4(mix(back_color, fore_color.rgb, fore_color.a), transparent_background ? fore_color.a : 1.0);\r\n"
"}\r\n"
"\r\n"
"vec4 non_svg_color()\r\n"
"{\r\n"
"    // takes foreground from texture\r\n"
"    vec4 color = texture2D(texture, tex_coords);\r\n"
"    return vec4(color.rgb, transparent_background ? color.a * 0.25 : color.a);\r\n"
"}\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_FragColor = svg_source ? svg_color() : non_svg_color();\r\n"
"}\r\n"
;

const std::string printbed_vs =
"#version 110\r\n"
"\r\n"
"attribute vec3 v_position;\r\n"
"attribute vec2 v_tex_coords;\r\n"
"\r\n"
"varying vec2 tex_coords;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_Position = gl_ModelViewProjectionMatrix * vec4(v_position.x, v_position.y, v_position.z, 1.0);\r\n"
"	// the following line leads to crash on some Intel graphics card\r\n"
"    //gl_Position = gl_ModelViewProjectionMatrix * vec4(v_position, 1.0);\r\n"
"    tex_coords = v_tex_coords;\r\n"
"}\r\n"
;

const std::string toolpaths_lines_fs =
"#version 110\r\n"
"\r\n"
"// normalized values for (-0.6/1.31, 0.6/1.31, 1./1.31)\r\n"
"const vec3 LIGHT_TOP_DIR = vec3(-0.4574957, 0.4574957, 0.7624929);\r\n"
"const vec3 LIGHT_FRONT_DIR = vec3(0.0, 0.0, 1.0);\r\n"
"\r\n"
"// x = ambient, y = top diffuse, z = front diffuse, w = global\r\n"
"uniform vec4 light_intensity;\r\n"
"uniform vec4 uniform_color;\r\n"
"\r\n"
"varying vec3 eye_normal;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    vec3 normal = normalize(eye_normal);\r\n"
"\r\n"
"    // Compute the cos of the angle between the normal and lights direction. The light is directional so the direction is constant for every vertex.\r\n"
"    // Since these two are normalized the cosine is the dot product. Take the abs value to light the lines no matter in which direction the normal points.\r\n"
"    float NdotL = abs(dot(normal, LIGHT_TOP_DIR));\r\n"
"\r\n"
"    float intensity = light_intensity.x + NdotL * light_intensity.y;\r\n"
"\r\n"
"    // Perform the same lighting calculation for the 2nd light source.\r\n"
"    NdotL = abs(dot(normal, LIGHT_FRONT_DIR));\r\n"
"    intensity += NdotL * light_intensity.z;    \r\n"
"\r\n"
"    gl_FragColor = vec4(uniform_color.rgb * light_intensity.w * intensity, uniform_color.a);\r\n"
"}\r\n"
;

const std::string toolpaths_lines_vs =
"#version 110\r\n"
"\r\n"
"varying vec3 eye_normal;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\r\n"
"    eye_normal = gl_NormalMatrix * gl_Normal;\r\n"
"}\r\n"
;

const std::string variable_layer_height_fs =
"#version 110\r\n"
"\r\n"
"#define M_PI 3.1415926535897932384626433832795\r\n"
"\r\n"
"// 2D texture (1D texture split by the rows) of color along the object Z axis.\r\n"
"uniform sampler2D z_texture;\r\n"
"// Scaling from the Z texture rows coordinate to the normalized texture row coordinate.\r\n"
"uniform float z_to_texture_row;\r\n"
"uniform float z_texture_row_to_normalized;\r\n"
"uniform float z_cursor;\r\n"
"uniform float z_cursor_band_width;\r\n"
"\r\n"
"// x = tainted, y = specular;\r\n"
"varying vec2 intensity;\r\n"
"\r\n"
"varying float object_z;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    float object_z_row = z_to_texture_row * object_z;\r\n"
"    // Index of the row in the texture.\r\n"
"    float z_texture_row = floor(object_z_row);\r\n"
"    // Normalized coordinate from 0. to 1.\r\n"
"    float z_texture_col = object_z_row - z_texture_row;\r\n"
"    float z_blend = 0.25 * cos(min(M_PI, abs(M_PI * (object_z - z_cursor) * 1.8 / z_cursor_band_width))) + 0.25;\r\n"
"    // Calculate level of detail from the object Z coordinate.\r\n"
"    // This makes the slowly sloping surfaces to be shown with high detail (with stripes),\r\n"
"    // and the vertical surfaces to be shown with low detail (no stripes)\r\n"
"    float z_in_cells = object_z_row * 190.;\r\n"
"    // Gradient of Z projected on the screen.\r\n"
"    float dx_vtc = dFdx(z_in_cells);\r\n"
"    float dy_vtc = dFdy(z_in_cells);\r\n"
"    float lod = clamp(0.5 * log2(max(dx_vtc * dx_vtc, dy_vtc * dy_vtc)), 0., 1.);\r\n"
"    // Sample the Z texture. Texture coordinates are normalized to <0, 1>.\r\n"
"    vec4 color = vec4(0.25, 0.25, 0.25, 1.0);\r\n"
"    if (z_texture_row >= 0.0)\r\n"
"        color = mix(texture2D(z_texture, vec2(z_texture_col, z_texture_row_to_normalized * (z_texture_row + 0.5    )), -10000.),\r\n"
"                    texture2D(z_texture, vec2(z_texture_col, z_texture_row_to_normalized * (z_texture_row * 2. + 1.)),  10000.), lod);            \r\n"
"    // Mix the final color.\r\n"
"    gl_FragColor = vec4(vec3(intensity.y), 1.0) +  intensity.x * mix(color, vec4(1.0, 1.0, 0.0, 1.0), z_blend);\r\n"
"}\r\n"
;

const std::string variable_layer_height_vs =
"#version 110\r\n"
"\r\n"
"#define INTENSITY_CORRECTION 0.6\r\n"
"\r\n"
"const vec3 LIGHT_TOP_DIR = vec3(-0.4574957, 0.4574957, 0.7624929);\r\n"
"#define LIGHT_TOP_DIFFUSE    (0.8 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SPECULAR   (0.125 * INTENSITY_CORRECTION)\r\n"
"#define LIGHT_TOP_SHININESS  20.0\r\n"
"\r\n"
"const vec3 LIGHT_FRONT_DIR = vec3(0.6985074, 0.1397015, 0.6985074);\r\n"
"#define LIGHT_FRONT_DIFFUSE  (0.3 * INTENSITY_CORRECTION)\r\n"
"//#define LIGHT_FRONT_SPECULAR (0.0 * INTENSITY_CORRECTION)\r\n"
"//#define LIGHT_FRONT_SHININESS 5.0\r\n"
"\r\n"
"#define INTENSITY_AMBIENT    0.3\r\n"
"\r\n"
"uniform mat4 volume_world_matrix;\r\n"
"uniform float object_max_z;\r\n"
"\r\n"
"// x = tainted, y = specular;\r\n"
"varying vec2 intensity;\r\n"
"\r\n"
"varying float object_z;\r\n"
"\r\n"
"void main()\r\n"
"{\r\n"
"    // First transform the normal into camera space and normalize the result.\r\n"
"    vec3 normal = normalize(gl_NormalMatrix * gl_Normal);\r\n"
"    \r\n"
"    // Compute the cos of the angle between the normal and lights direction. The light is directional so the direction is constant for every vertex.\r\n"
"    // Since these two are normalized the cosine is the dot product. We also need to clamp the result to the [0,1] range.\r\n"
"    float NdotL = max(dot(normal, LIGHT_TOP_DIR), 0.0);\r\n"
"\r\n"
"    intensity.x = INTENSITY_AMBIENT + NdotL * LIGHT_TOP_DIFFUSE;\r\n"
"    vec3 position = (gl_ModelViewMatrix * gl_Vertex).xyz;\r\n"
"    intensity.y = LIGHT_TOP_SPECULAR * pow(max(dot(-normalize(position), reflect(-LIGHT_TOP_DIR, normal)), 0.0), LIGHT_TOP_SHININESS);\r\n"
"\r\n"
"    // Perform the same lighting calculation for the 2nd light source (no specular)\r\n"
"    NdotL = max(dot(normal, LIGHT_FRONT_DIR), 0.0);\r\n"
"    \r\n"
"    intensity.x += NdotL * LIGHT_FRONT_DIFFUSE;\r\n"
"\r\n"
"    // Scaled to widths of the Z texture.\r\n"
"    if (object_max_z > 0.0)\r\n"
"        // when rendering the overlay\r\n"
"        object_z = object_max_z * gl_MultiTexCoord0.y;\r\n"
"    else\r\n"
"        // when rendering the volumes\r\n"
"        object_z = (volume_world_matrix * gl_Vertex).z;\r\n"
"        \r\n"
"    gl_Position = ftransform();\r\n"
"}\r\n"
;

#endif /* slic3r_BBL_Shader_Programs_hpp_ */