
var Test_MakerlabList={
	"result": 0,
	"list": [
		{
			"id": 1,
			"thumbnail": "https://public-cdn.bblmw.com/content-generator/nameplate/nameplate_card.png",
			"jumpTo": "makerlab/makeMySign",
			"info": {
				"en": {
					"name": "Make My Sign",
					"description": "Name plate, badge, sign, light box, anything flat",
					"author": "Makerlab official"
				},
				"zh_CN": {
					"name": "标牌定制器",
					"description": "办公桌铭牌、居家挂牌、名片、标签、钥匙扣轻松创作",
					"author": "Makerlab 官方"
				}
			}
		},
		{
			"id": 2,
			"thumbnail": "https://public-cdn.bblmw.com/content-generator/vase/vase_card.jpeg",
			"jumpTo": "makerlab/makeMyVase",
			"info": {
				"en": {
					"name": "Make My Vase",
					"description": "Craft your dream vase by clicks",
					"author": "Makerlab official"
				},
				"zh_CN": {
					"name": "花瓶生成器",
					"description": "点击制作你梦想中的花瓶",
					"author": "Makerlab 官方"
				}
			}
		},
		{
			"id": 3,
			"thumbnail": "https://public-cdn.bblmw.com/content-generator/pixel/pixel_card.jpg",
			"jumpTo": "makerlab/pixelPuzzleMaker",
			"info": {
				"en": {
					"name": "Pixel Puzzle Maker",
					"description": "Pixelize it. Print It. Build you own pixel puzzle",
					"author": "Makerlab official"
				},
				"zh_CN": {
					"name": "像素拼图生成器",
					"description": "定制你专属的像素拼图",
					"author": "Makerlab 官方"
				}
			}
		}
	]
};

var Test_PrintTaskList={
	"command": "printhistory_task_show",
	"total": 15,
	"hits": [
		{
			"id": 3622536,
			"designId": 374186,
			"designTitle": "首发模型0914 1409 --0918 12：00改为独家",
			"designTitleTranslated": "Exclusive model debut 0914 1409 --0918 12:00",
			"instanceId": 32755,
			"modelId": "CNQ72af310210f64b",
			"title": "首发变独家",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/CNQ72af310210f64b/4007130/instance/plate_1.png",
			"status": 3,
			"feedbackStatus": 1,
			"startTime": "2024-09-20T09:56:22Z",
			"endTime": "2024-09-20T09:56:32Z",
			"weight": 0,
			"length": 0,
			"costTime": 0,
			"profileId": 4007130,
			"plateIndex": 1,
			"plateName": "",
			"deviceId": "03W09A380900239",
			"amsDetailMapping": [
				{
					"ams": 0,
					"sourceColor": "FFFFFFFF",
					"targetColor": "",
					"filamentId": "",
					"filamentType": "PLA",
					"targetFilamentType": "PLA",
					"weight": 0
				}
			],
			"mode": "user_slice",
			"isPublicProfile": false,
			"isPrintable": true,
			"isDelete": false,
			"deviceModel": "X1E",
			"deviceName": "3DP-03W-239",
			"bedType": "Cool Plate"
		},
		{
			"id": 3622535,
			"designId": 374186,
			"designTitle": "首发模型0914 1409 --0918 12：00改为独家",
			"designTitleTranslated": "Exclusive model debut 0914 1409 --0918 12:00",
			"instanceId": 32755,
			"modelId": "CNQ72af310210f64b",
			"title": "首发变独家",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/CNQ72af310210f64b/4007130/instance/plate_1.png",
			"status": 3,
			"feedbackStatus": 1,
			"startTime": "2024-09-20T09:55:42Z",
			"endTime": "2024-09-20T09:56:00Z",
			"weight": 0,
			"length": 0,
			"costTime": 0,
			"profileId": 4007130,
			"plateIndex": 1,
			"plateName": "",
			"deviceId": "03W09A380900239",
			"amsDetailMapping": [
				{
					"ams": 0,
					"sourceColor": "FFFFFFFF",
					"targetColor": "",
					"filamentId": "",
					"filamentType": "PLA",
					"targetFilamentType": "PLA",
					"weight": 0
				}
			],
			"mode": "cloud_slice",
			"isPublicProfile": true,
			"isPrintable": true,
			"isDelete": false,
			"deviceModel": "X1E",
			"deviceName": "3DP-03W-239",
			"bedType": "Cool Plate"
		},
		{
			"id": 3622505,
			"designId": 374186,
			"designTitle": "首发模型0914 1409 --0918 12：00改为独家",
			"designTitleTranslated": "Exclusive model debut 0914 1409 --0918 12:00",
			"instanceId": 32755,
			"modelId": "CNQ72af310210f64b",
			"title": "首发变独家",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/cache/1/CNQ72af310210f64b/4007130/3mf/3/REP1/Metadata/plate_3.png",
			"status": 2,
			"feedbackStatus": 1,
			"startTime": "2024-09-20T06:38:33Z",
			"endTime": "2024-09-20T08:27:56Z",
			"weight": 53.54,
			"length": 1766,
			"costTime": 6376,
			"profileId": 4007130,
			"plateIndex": 3,
			"plateName": "",
			"deviceId": "03W09A380900239",
			"amsDetailMapping": [
				{
					"ams": 0,
					"sourceColor": "FFFFFFFF",
					"targetColor": "FFFFFFFF",
					"filamentId": "",
					"filamentType": "PLA",
					"targetFilamentType": "PLA",
					"weight": 53.54
				}
			],
			"mode": "cloud_slice",
			"isPublicProfile": true,
			"isPrintable": true,
			"isDelete": false,
			"deviceModel": "X1E",
			"deviceName": "3DP-03W-239",
			"bedType": "Cool Plate"
		},
		{
			"id": 3622504,
			"designId": 374186,
			"designTitle": "首发模型0914 1409 --0918 12：00改为独家",
			"designTitleTranslated": "Exclusive model debut 0914 1409 --0918 12:00",
			"instanceId": 32755,
			"modelId": "CNQ72af310210f64b",
			"title": "首发变独家",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/cache/1/CNQ72af310210f64b/4007130/3mf/3/%23A0E20EFF/REP1/Metadata/plate_3.png",
			"status": 2,
			"feedbackStatus": 1,
			"startTime": "2024-09-20T06:38:18Z",
			"endTime": "2024-09-20T08:38:35Z",
			"weight": 56.09,
			"length": 1766,
			"costTime": 7131,
			"profileId": 4007130,
			"plateIndex": 3,
			"plateName": "",
			"deviceId": "00W00A242600023",
			"amsDetailMapping": [
				{
					"ams": 1,
					"sourceColor": "FFFFFFFF",
					"targetColor": "A0E20EFF",
					"filamentId": "",
					"filamentType": "PLA",
					"targetFilamentType": "PLA",
					"weight": 56.09
				}
			],
			"mode": "cloud_slice",
			"isPublicProfile": true,
			"isPrintable": true,
			"isDelete": false,
			"deviceModel": "X1",
			"deviceName": "025",
			"bedType": "Cool Plate"
		},
		{
			"id": 3622499,
			"designId": 374186,
			"designTitle": "首发模型0914 1409 --0918 12：00改为独家",
			"designTitleTranslated": "Exclusive model debut 0914 1409 --0918 12:00",
			"instanceId": 32755,
			"modelId": "CNQ72af310210f64b",
			"title": "首发变独家",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/cache/1/CNQ72af310210f64b/4007130/3mf/3/REP1/Metadata/plate_3.png",
			"status": 2,
			"feedbackStatus": 1,
			"startTime": "2024-09-20T04:12:14Z",
			"endTime": "2024-09-20T06:02:16Z",
			"weight": 53.54,
			"length": 1766,
			"costTime": 6376,
			"profileId": 4007130,
			"plateIndex": 3,
			"plateName": "",
			"deviceId": "03W09A380900239",
			"amsDetailMapping": [
				{
					"ams": 0,
					"sourceColor": "FFFFFFFF",
					"targetColor": "FFFFFFFF",
					"filamentId": "",
					"filamentType": "PLA",
					"targetFilamentType": "PLA",
					"weight": 53.54
				}
			],
			"mode": "cloud_slice",
			"isPublicProfile": true,
			"isPrintable": true,
			"isDelete": false,
			"deviceModel": "X1E",
			"deviceName": "3DP-03W-239",
			"bedType": "Cool Plate"
		}
	]
}

var Test_4UModelList={
	"hits": [
		{
			"id": 374202,
			"title": "0920 可定制",
			"titleTranslated": "0920 Customizable",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/CNQc553e8906eaff0/design/2024-09-20_7cf6087c009.jpg",
			"likeCount": 0,
			"collectionCount": 1,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 0,
			"commentCount": 0,
			"readCount": 0,
			"designCreator": {
				"uid": 1074649781,
				"name": "xiaohuan.li888888888888888888888888888",
				"avatar": "https://public-us-cdn.bambulab.net/avatar/9a12d850-539a-11ef-bcfb-2953b84d62de.jpg",
				"fanCount": 6,
				"followCount": 6,
				"createTime": "2023-08-29T07:06:16Z",
				"certificated": true,
				"handle": "xiaohuan.li6667",
				"level": 30,
				"gradeType": 4
			},
			"createTime": "2024-09-20T03:10:43Z",
			"nsfw": false,
			"hotScore": 794,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": true,
			"pickReason": "",
			"isPrintable": true,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": true,
			"contest": {
				"contestId": 124,
				"rank": 0,
				"status": 1,
				"contestName": "0718 contest",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 4,
			"customizedByMakerLab": true,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 0,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"4|0.93\"],\"rk\":\"-0.04|0\"}",
			"modelId": "CNQc553e8906eaff0"
		},
		{
			"id": 374215,
			"title": "jeep",
			"titleTranslated": "",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/CNQ5da5ab69430323/design/2024-09-20_ef0049a4b5026.jpg",
			"likeCount": 0,
			"collectionCount": 1,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 1,
			"commentCount": 1,
			"readCount": 0,
			"designCreator": {
				"uid": 415112594,
				"name": "Yifan Wu",
				"avatar": "https://public-dev-cdn.bambulab.net/avatar/415112594/2023-05-06_1f35259225fad.jpg",
				"fanCount": 14,
				"followCount": 14,
				"createTime": "2022-04-07T09:52:23Z",
				"certificated": false,
				"handle": "wuyifan",
				"level": 11,
				"gradeType": 1
			},
			"createTime": "2024-09-20T12:00:13Z",
			"nsfw": false,
			"hotScore": 2726,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": false,
			"pickReason": "",
			"isPrintable": true,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": true,
			"contest": {
				"contestId": 0,
				"rank": 0,
				"status": 0,
				"contestName": "",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 7,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 3,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"7|1\"],\"rk\":\"-0.11|1\"}",
			"modelId": "CNQ5da5ab69430323"
		},
		{
			"id": 374216,
			"title": "小迷宫",
			"titleTranslated": "mini maze",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/DSM00000000374216/design/2024-09-20_e31bc38f1cef9.webp",
			"likeCount": 0,
			"collectionCount": 0,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 2,
			"commentCount": 0,
			"readCount": 0,
			"designCreator": {
				"uid": 415112594,
				"name": "Yifan Wu",
				"avatar": "https://public-dev-cdn.bambulab.net/avatar/415112594/2023-05-06_1f35259225fad.jpg",
				"fanCount": 14,
				"followCount": 14,
				"createTime": "2022-04-07T09:52:23Z",
				"certificated": false,
				"handle": "wuyifan",
				"level": 11,
				"gradeType": 1
			},
			"createTime": "2024-09-20T12:44:02Z",
			"nsfw": false,
			"hotScore": 1891,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": false,
			"pickReason": "",
			"isPrintable": true,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": true,
			"contest": {
				"contestId": 0,
				"rank": 0,
				"status": 0,
				"contestName": "",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 7,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 1,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"7|0.92\"],\"rk\":\"-0.17|2\"}",
			"modelId": "CNQ581249e18cec42"
		},
		{
			"id": 374218,
			"title": "运营开启独家未达标用户",
			"titleTranslated": "The following content requires translation:\nExclusive unmet user operations have been initiated.",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/CNQf2d9054da20bfe/design/2024-09-23_d4d635adef548.jpg",
			"likeCount": 0,
			"collectionCount": 0,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 11,
			"commentCount": 0,
			"readCount": 0,
			"designCreator": {
				"uid": 1375262870,
				"name": "XNCS025",
				"avatar": "https://oss-cdn.bambulab.com/default-avatar.png",
				"fanCount": 1,
				"followCount": 1,
				"createTime": "2023-03-07T02:14:57Z",
				"certificated": false,
				"handle": "XNCS025",
				"level": 4,
				"gradeType": 0
			},
			"createTime": "2024-09-23T07:17:13Z",
			"nsfw": false,
			"hotScore": 2447,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": false,
			"pickReason": "",
			"isPrintable": true,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": true,
			"contest": {
				"contestId": 0,
				"rank": 0,
				"status": 0,
				"contestName": "",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 7,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 0,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"7|0.96\"],\"rk\":\"-0.21|3\"}",
			"modelId": "CNQf2d9054da20bfe"
		},
		{
			"id": 374229,
			"title": "测试一下定时任务",
			"titleTranslated": "Test the scheduled task",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/CNQe4b47ef2e53023/design/2024-09-23_ed5de35b423cc.webp",
			"likeCount": 0,
			"collectionCount": 0,
			"shareCount": 0,
			"printCount": 2,
			"downloadCount": 2,
			"commentCount": 0,
			"readCount": 0,
			"designCreator": {
				"uid": 1812646376,
				"name": "银鱼test2",
				"avatar": "https://public-cdn.bblmw.com/default/avatar.png",
				"fanCount": 1,
				"followCount": 1,
				"createTime": "2024-09-12T07:02:50Z",
				"certificated": false,
				"handle": "user_1812646376",
				"level": 10,
				"gradeType": 1
			},
			"createTime": "2024-09-23T10:42:15Z",
			"nsfw": false,
			"hotScore": 1442,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": false,
			"pickReason": "",
			"isPrintable": true,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": false,
			"contest": {
				"contestId": 0,
				"rank": 0,
				"status": 0,
				"contestName": "",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 7,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 0,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"7|0.88\"],\"rk\":\"-0.22|4\"}",
			"modelId": "CNQe4b47ef2e53023"
		},
		{
			"id": 371892,
			"title": "测试竞赛",
			"titleTranslated": "",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/DSM00000000371892/design/2024-03-28_6875c4e16c667.jpg",
			"likeCount": 1,
			"collectionCount": 1,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 1,
			"commentCount": 0,
			"readCount": 0,
			"designCreator": {
				"uid": 3185390264,
				"name": "fang.nie",
				"avatar": "https://public-dev-cdn.bambulab.net/avatar/3185390264/2024-02-26_fc5558ccc29f1.jpg",
				"fanCount": 6,
				"followCount": 6,
				"createTime": "2022-05-11T07:56:50Z",
				"certificated": false,
				"handle": "fang.nie",
				"level": 8,
				"gradeType": 1
			},
			"createTime": "2024-03-28T07:59:10Z",
			"nsfw": false,
			"hotScore": 0,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": true,
			"pickReason": "",
			"isPrintable": false,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": false,
			"contest": {
				"contestId": 75,
				"rank": 0,
				"status": 1,
				"contestName": "0306进行中的竞赛",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 4,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 0,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"4|1\"],\"rk\":\"-0.28|5\"}",
			"modelId": ""
		},
		{
			"id": 374114,
			"title": "打印时长超过20小时",
			"titleTranslated": "Printing duration exceeds 20 hours",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/CNQf47c4b034a745c/design/2024-08-30_2606102d038c5.webp",
			"likeCount": 0,
			"collectionCount": 0,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 0,
			"commentCount": 0,
			"readCount": 0,
			"designCreator": {
				"uid": 3345032319,
				"name": "Summer_lights",
				"avatar": "https://public-cdn.bambulab.com/default/avatar.png",
				"fanCount": 2,
				"followCount": 2,
				"createTime": "2023-08-04T08:43:14Z",
				"certificated": true,
				"handle": "Summer_lights",
				"level": 7,
				"gradeType": 1
			},
			"createTime": "2024-08-30T02:52:40Z",
			"nsfw": false,
			"hotScore": 0,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": true,
			"pickReason": "",
			"isPrintable": true,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": false,
			"contest": {
				"contestId": 0,
				"rank": 0,
				"status": 0,
				"contestName": "",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 4,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 0,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"4|0.86\"],\"rk\":\"-0.4|6\"}",
			"modelId": "CNQf47c4b034a745c"
		},
		{
			"id": 374044,
			"title": "恐龙模型",
			"titleTranslated": "Dinosaur Model",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/DSM00000000374044/design/2024-08-08_0cade4e99b18c.png",
			"likeCount": 2,
			"collectionCount": 2,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 1,
			"commentCount": 10,
			"readCount": 0,
			"designCreator": {
				"uid": 3603343695,
				"name": "龙井~qa",
				"avatar": "https://public-dev-cdn.bambulab.net/avatar/3603343695/2023-11-01_f32d53e210073.jpg",
				"fanCount": 12,
				"followCount": 12,
				"createTime": "2022-08-01T07:37:47Z",
				"certificated": false,
				"handle": "user_3603343695",
				"level": 10,
				"gradeType": 1
			},
			"createTime": "2024-08-08T08:09:44Z",
			"nsfw": false,
			"hotScore": 163,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": true,
			"pickReason": "",
			"isPrintable": true,
			"isOfficial": true,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": false,
			"contest": {
				"contestId": 0,
				"rank": 0,
				"status": 0,
				"contestName": "",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 4,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 4,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"4|0.79\"],\"rk\":\"-0.43|7\"}",
			"modelId": "CNQ1ff72338b76e42"
		},
		{
			"id": 374224,
			"title": "testing1",
			"titleTranslated": "",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/CNQ6d8c4e451cb1cb/design/2024-09-23_523ae314284da.webp",
			"likeCount": 0,
			"collectionCount": 0,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 0,
			"commentCount": 0,
			"readCount": 0,
			"designCreator": {
				"uid": 899054757,
				"name": "user_899054757",
				"avatar": "https://public-us-cdn.bambulab.net/avatar/bfe3d810-798b-11ef-bd70-27bc07e67d92.jpg",
				"fanCount": 0,
				"followCount": 0,
				"createTime": "2024-09-20T09:19:40Z",
				"certificated": false,
				"handle": "user_899054757",
				"level": 6,
				"gradeType": 0
			},
			"createTime": "2024-09-23T09:48:17Z",
			"nsfw": false,
			"hotScore": 0,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": false,
			"pickReason": "",
			"isPrintable": true,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": false,
			"contest": {
				"contestId": 0,
				"rank": 0,
				"status": 0,
				"contestName": "",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 7,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 0,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"7|0.56\"],\"rk\":\"-0.43|8\"}",
			"modelId": "CNQ6d8c4e451cb1cb"
		},
		{
			"id": 374227,
			"title": "test2",
			"titleTranslated": "",
			"cover": "https://public-dev-cdn.bambulab.net/makerworld/model/DSM00000000374227/design/2024-09-23_ff06b8ab9e468.jpg",
			"likeCount": 0,
			"collectionCount": 0,
			"shareCount": 0,
			"printCount": 0,
			"downloadCount": 0,
			"commentCount": 0,
			"readCount": 0,
			"designCreator": {
				"uid": 899054757,
				"name": "user_899054757",
				"avatar": "https://public-us-cdn.bambulab.net/avatar/bfe3d810-798b-11ef-bd70-27bc07e67d92.jpg",
				"fanCount": 0,
				"followCount": 0,
				"createTime": "2024-09-20T09:19:40Z",
				"certificated": false,
				"handle": "user_899054757",
				"level": 6,
				"gradeType": 0
			},
			"createTime": "2024-09-23T09:51:22Z",
			"nsfw": false,
			"hotScore": 0,
			"status": 1,
			"hasCollect": false,
			"hasLike": false,
			"hasDislike": false,
			"isStaffPicked": false,
			"pickReason": "",
			"isPrintable": false,
			"isOfficial": false,
			"isPointRedeemable": false,
			"pointRedeemDetail": {
				"price": 0,
				"sku": "",
				"status": 0
			},
			"isExclusive": false,
			"contest": {
				"contestId": 0,
				"rank": 0,
				"status": 0,
				"contestName": "",
				"contestStatus": 0,
				"comment": ""
			},
			"source": 7,
			"customizedByMakerLab": false,
			"preset": {
				"type": "",
				"filamentConfig": null,
				"printerConfig": null,
				"processConfig": null,
				"printerSettings": null,
				"file": {
					"name": "",
					"size": 0,
					"url": ""
				}
			},
			"coverLandscape": "",
			"coverPortrait": "",
			"boostCnt": 0,
			"bomsNeeded": false,
			"bannerTitle": "",
			"ext": "{\"rc\":[\"7|0.68\"],\"rk\":\"-0.49|9\"}",
			"modelId": ""
		}
	],
	"seed": 1149157380,
	"surplus": 32
};