name: Auto-assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  workflow_dispatch:

permissions: read-all
jobs:
  assign:
    name: Add to BambuStudio Development project
    runs-on: ubuntu-24.04
    if: github.event_name == 'issues' || github.event_name == 'pull_request'
    steps:
      - uses: actions/add-to-project@v2.0.0
        with:
          project-url: https://github.com/users/BenJule/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}
