name: Build Linux

on: [pull_request]

jobs:
  appimage-builder:
    name: Linux AppImage Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libgl1-mesa-dev libgtk-3-dev libxkbcommon-dev libunwind-dev libfuse2 -y
      - name: Install dependencies from BuildLinux.sh
        shell: bash
        run: sudo ./BuildLinux.sh -ur
      - name: Fix permissions
        shell: bash
        run: sudo chown $USER -R ./
      - name: Build deps
        id: cache_deps
        uses: actions/cache@v3
        env:
          cache-name: ${{ runner.os }}-cache-bambustudio_deps_x64
        with:
          path: ${{ github.workspace }}/deps/build/destdir
          key: build-${{ env.cache-name }}

      - if: ${{ steps.cache_deps.outputs.cache-hit != 'true' }}
        name: Build deps
        working-directory: ${{ github.workspace }}
        continue-on-error: true
        run: ./BuildLinux.sh -dsr

      - name: Build Studio
        shell: bash
        run: ./BuildLinux.sh -ir
      - uses: actions/upload-artifact@v3
        with:
          name: BambuStudio_Linux
          path: './build/BambuStudio_ubu64.AppImage'

  appimage-builder-u2004:
    name: Linux AppImage Build Ubuntu 20.04

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      - name: Build
        shell: bash
        run: |
          rm -rf build
          podman buildx build --build-arg BUILD_LINUX_EXTRA_ARGS=-r -t bambu-studio-builder:latest .
          podman run -d -it --name bambu-studio-builder bambu-studio-builder:latest /bin/bash -c 'tail -f /dev/null'
          podman cp bambu-studio-builder:/BambuStudio/build/BambuStudio_ubu64.AppImage ./
          podman stop bambu-studio-builder
          podman rm bambu-studio-builder
      - uses: actions/upload-artifact@v3
        with:
          name: BambuStudio_Linux
          path: './BambuStudio_ubu64.AppImage'
