name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-2025
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: Bambulab.BambuStudio
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: '\.exe$'